/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as QuestionarioRouteImport } from './routes/questionario'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as MentoraIndexRouteImport } from './routes/mentora.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionarioRoute = QuestionarioRouteImport.update({
  id: '/questionario',
  path: '/questionario',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoraIndexRoute = MentoraIndexRouteImport.update({
  id: '/mentora/',
  path: '/mentora/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/questionario': typeof QuestionarioRoute
  '/sobre': typeof SobreRoute
  '/mentora/': typeof MentoraIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/questionario': typeof QuestionarioRoute
  '/sobre': typeof SobreRoute
  '/mentora': typeof MentoraIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/questionario': typeof QuestionarioRoute
  '/sobre': typeof SobreRoute
  '/mentora/': typeof MentoraIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assinatura'
    | '/cadastro'
    | '/login'
    | '/perfil'
    | '/questionario'
    | '/sobre'
    | '/mentora/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assinatura'
    | '/cadastro'
    | '/login'
    | '/perfil'
    | '/questionario'
    | '/sobre'
    | '/mentora'
  id:
    | '__root__'
    | '/'
    | '/assinatura'
    | '/cadastro'
    | '/login'
    | '/perfil'
    | '/questionario'
    | '/sobre'
    | '/mentora/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssinaturaRoute: typeof AssinaturaRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  QuestionarioRoute: typeof QuestionarioRoute
  SobreRoute: typeof SobreRoute
  MentoraIndexRoute: typeof MentoraIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionario': {
      id: '/questionario'
      path: '/questionario'
      fullPath: '/questionario'
      preLoaderRoute: typeof QuestionarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentora/': {
      id: '/mentora/'
      path: '/mentora'
      fullPath: '/mentora/'
      preLoaderRoute: typeof MentoraIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssinaturaRoute: AssinaturaRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  QuestionarioRoute: QuestionarioRoute,
  SobreRoute: SobreRoute,
  MentoraIndexRoute: MentoraIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
